name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: release-${{ github.sha }}
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-libadwaita mingw-w64-ucrt-x86_64-python-gobject mingw-w64-ucrt-x86_64-python-yaml mingw-w64-ucrt-x86_64-python-requests mingw-w64-ucrt-x86_64-python-pillow mingw-w64-ucrt-x86_64-desktop-file-utils mingw-w64-ucrt-x86_64-ca-certificates mingw-w64-ucrt-x86_64-meson git

      - name: Compile
        shell: msys2 {0}
        run: |
          meson setup _build
          ninja -C _build install
          pacman --noconfirm -Rs mingw-w64-ucrt-x86_64-desktop-file-utils mingw-w64-ucrt-x86_64-meson git

      - name: Test
        shell: msys2 {0}
        run: |
          set +e
          timeout 2 cartridges; [ "$?" -eq "124" ]

      - name: Inno Setup
        run: iscc ".\_build\build-aux\windows\Cartridges.iss"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Installer
          path: _build/build-aux/windows/Output/Cartridges Windows.exe
